debug: True
generation_count: 1


mongo:
  # uri: mongodb://root:Js17EZXZNFtIWnjKLlEtJifx@s7.liara.ir:31102/?authSource=admin
  uri: mongodb://root:cKXnd8qb34wQQGOhGzsJuAYr@s8.liara.ir:30080/?authSource=admin&replicaSet=rs0
