dir:
  project: .
  templates: ./templates/main
  questions: ./modules
  result: ./template_engine/result
  dataset: ./datasets
  empty_template: ./config/samples/empty_template.json
  template_schema: ./config/samples/template_schema.json
  template_formatter: ./config/samples/template_formatter.json
  sample_questions: ./config/samples/sample_questions.json


template:
  min_vote: 2

  states:
    - idea
    - writing
    - repair
    - ready
    - verified
    - in_use

  tests:
    idea:
      required:

    writing:
      required:
        - duplication
        - acceptance
        - data

    repair:
      required:
        - structure
        - schema

    ready:
      required:
        - generation

    verified:
      required:
        - manual

    in_use:
      required:
        - usage_tagging


format:
  question:
    exist: "&&"
    not-exotst: "&"

file_formats:
  photo:
    - png
    - jpg
    - jpeg
    - gif
    - svg

  video:
    - mp4
    - 3gp
    - avi
    - mov
    - flv
    - wmv

  audio:
    - mp3
    - m4a
    - flac
