debug: True
language: fa
main_server_ip: https://31.184.132.183:30000
template_new_server: https://31.184.132.183:30000/template/new

dir:
  project: .
  templates: ./templates/main
  questions: ./modules
  result: ./template_engine/result
  dataset: ./datasets
  empty_template: ./config/samples/empty_template.json
  template_schema: ./config/samples/template_schema.json
  template_formatter: ./config/samples/template_formatter.json
  sample_questions: ./config/samples/sample_questions.json

datasets:
  - movie
  - director
  - song
  - actor
  - footballPlayer
  - footballTeam
  - quote
  - country
  - book
  - name
  - word
  - volleyballTeam

mongo:
  uri: mongodb://root:Js17EZXZNFtIWnjKLlEtJifx@s7.liara.ir:31102/?authSource=admin


template:
  min_vote: 2

  states:
    - idea
    - writing
    - repair
    - ready
    - verified
    - in_use

  tests:
    idea:
      required:

    writing:
      required:
        - duplication
        - acceptance
        - data

    repair:
      required:
        - structure
        - schema

    ready:
      required:
        - generation

    verified:
      required:
        - manual

    in_use:
      required:
        - usage_tagging

format:
  question:
    exist: "&&"
    not-exotst: "&"

file_formats:
  photo:
    - png
    - jpg
    - jpeg
    - gif
    - svg

  video:
    - mp4
    - 3gp
    - avi
    - mov
    - flv
    - wmv

  audio:
    - mp3
    - m4a
    - flac
